"""tundravm: declarative TDX VM images.

A :class:`Recipe` (recipe-wide settings, a ``common`` :class:`Fragment` and its
:class:`Variant` overlays) is the whole public model; ``resolve``/``lint``/
``lower``/``load`` and the lifecycle (``compile``, ``lock``, ``fetch``, ``bake``,
``read_artifacts``, ``verify_artifact``, ``doctor``) take one; ``attest`` checks a
running image's quote against a verifier policy, ``sbom`` lists what a baked
artifact contains and ``evidence`` gathers an auditor's record of a bake.
``diff``, ``measure`` and ``deploy`` are ``tundravm.declarative.diff``/``measure``/
``deploy`` (at the top level those names are modules). The shipped fragments are
in :mod:`tundravm.declarative.utils`.
"""

__version__ = "0.1.0"

from .attestation import Attestation, attest
from .declarative import (
    Artifact,
    Azure,
    Backend,
    Build,
    Cargo,
    Debloat,
    Declaration,
    Deployment,
    Diagnostic,
    Directory,
    Disk,
    Dotnet,
    Entry,
    FetchedSource,
    File,
    Fragment,
    Gcp,
    Git,
    Go,
    Group,
    Hook,
    Http,
    Imported,
    Init,
    Install,
    Kernel,
    Key,
    Lock,
    Measurements,
    Mkosi,
    Package,
    Partition,
    Pin,
    Policy,
    Qemu,
    Recipe,
    Repository,
    Resolved,
    RuntimeTools,
    Sbom,
    Schema,
    Secret,
    SecretEnv,
    SecretFile,
    Secrets,
    Service,
    Setting,
    Template,
    Tree,
    Unit,
    User,
    Variant,
    bake,
    compile,
    doctor,
    fetch,
    import_tree,
    lint,
    load,
    lock,
    lock_status,
    lower,
    read_artifacts,
    read_lock,
    resolve,
    resolve_all,
    sbom,
    verify_artifact,
    write_lock,
)
from .errors import (
    ArtifactError,
    AttestationError,
    BackendExecutionError,
    DeploymentError,
    LintError,
    LockfileError,
    MeasurementError,
    PolicyError,
    ReproducibilityError,
    SourceError,
    StateError,
    TdxError,
    ValidationError,
)
from .evidence import Evidence, evidence
from .explain import Why, explain_why
from .recipe import load_recipe

__all__ = [
    "Artifact",
    "ArtifactError",
    "Attestation",
    "AttestationError",
    "Azure",
    "Backend",
    "BackendExecutionError",
    "Build",
    "Cargo",
    "Debloat",
    "Declaration",
    "Deployment",
    "DeploymentError",
    "Diagnostic",
    "Directory",
    "Disk",
    "Dotnet",
    "Entry",
    "Evidence",
    "FetchedSource",
    "File",
    "Fragment",
    "Gcp",
    "Git",
    "Go",
    "Group",
    "Hook",
    "Http",
    "Imported",
    "Init",
    "Install",
    "Kernel",
    "Key",
    "LintError",
    "Lock",
    "LockfileError",
    "MeasurementError",
    "Measurements",
    "Mkosi",
    "Package",
    "Partition",
    "Pin",
    "Policy",
    "PolicyError",
    "Qemu",
    "Recipe",
    "Repository",
    "ReproducibilityError",
    "Resolved",
    "RuntimeTools",
    "Sbom",
    "Schema",
    "Secret",
    "SecretEnv",
    "SecretFile",
    "Secrets",
    "Service",
    "Setting",
    "SourceError",
    "StateError",
    "TdxError",
    "Template",
    "Tree",
    "Unit",
    "User",
    "ValidationError",
    "Variant",
    "Why",
    "attest",
    "bake",
    "compile",
    "doctor",
    "evidence",
    "explain_why",
    "fetch",
    "import_tree",
    "lint",
    "load",
    "load_recipe",
    "lock",
    "lock_status",
    "lower",
    "read_artifacts",
    "read_lock",
    "resolve",
    "resolve_all",
    "sbom",
    "verify_artifact",
    "write_lock",
    "__version__",
]
