"""Public package entrypoint for the TDX VM SDK.

The declarative API (``Recipe``, ``Fragment``, ``Variant``, the declarations,
``resolve``/``lint``/``lower``/``load``) and its lifecycle (``compile``,
``lock``, ``bake``, ``read_artifacts``, ``doctor`` and their result types) are
the public surface. ``diff``, ``measure`` and ``deploy`` are reached as
``tundravm.declarative.diff``/``measure``/``deploy``: at the top level those
names are the ``tundravm.diff``/``tundravm.measure``/``tundravm.deploy`` modules. The fluent
``Image``/``Profile`` names below it remain importable while the compiler is
reached through them; ``Kernel`` is still the fluent kernel spec (the
declarative one is ``tundravm.declarative.Kernel``).
"""

__version__ = "0.1.0"

from .declarative import (
    Artifact,
    Azure,
    Backend,
    Build,
    Debloat,
    Declaration,
    Deployment,
    Diagnostic,
    Directory,
    Disk,
    Entry,
    File,
    Fragment,
    Gcp,
    Git,
    Group,
    Hook,
    Http,
    Init,
    Install,
    Key,
    Lock,
    Measurements,
    Mkosi,
    Package,
    Partition,
    Pin,
    Qemu,
    Recipe,
    Repository,
    Resolved,
    RuntimeTools,
    Schema,
    Secret,
    SecretEnv,
    SecretFile,
    Secrets,
    Setting,
    Tree,
    Unit,
    User,
    Variant,
    bake,
    compile,
    doctor,
    lint,
    load,
    lock,
    lock_status,
    lower,
    read_artifacts,
    read_lock,
    resolve,
    resolve_all,
    write_lock,
)
from .diff import FileChange, TreeDiff
from .errors import (
    BackendExecutionError,
    DeploymentError,
    LintError,
    LockfileError,
    MeasurementError,
    PolicyError,
    ReproducibilityError,
    StateError,
    TdxError,
    ValidationError,
)
from .image import Image
from .measure import PlaceholderMeasurementWarning
from .models import (
    BakeRequest,
    BakeResult,
    CompileResult,
    DebloatConfig,
    Kernel,
    ProfileState,
    RecipeState,
    SecretSchema,
    SecretSpec,
    SecretTarget,
)
from .options import MkosiOptions
from .policy import Policy
from .profile import Profile
from .recipe import load_recipe
from .source import (
    CargoBuild,
    DotnetBuild,
    GitSource,
    GoBuild,
    HttpSource,
    ScriptBuild,
    SourceBuild,
)

__all__ = [
    # Declarative API
    "Artifact",
    "Azure",
    "Backend",
    "Deployment",
    "Entry",
    "Gcp",
    "Lock",
    "Measurements",
    "Pin",
    "Qemu",
    "Tree",
    "bake",
    "compile",
    "doctor",
    "lock",
    "lock_status",
    "read_artifacts",
    "read_lock",
    "write_lock",
    "Build",
    "Debloat",
    "Declaration",
    "Diagnostic",
    "Directory",
    "Disk",
    "File",
    "Fragment",
    "Git",
    "Group",
    "Hook",
    "Http",
    "Init",
    "Install",
    "Key",
    "Mkosi",
    "Package",
    "Partition",
    "Recipe",
    "Repository",
    "Resolved",
    "RuntimeTools",
    "Schema",
    "Secret",
    "SecretEnv",
    "SecretFile",
    "Secrets",
    "Setting",
    "Unit",
    "User",
    "Variant",
    "lint",
    "load",
    "lower",
    "resolve",
    "resolve_all",
    # Fluent frontend (internal lowering target; removed in a later stage)
    "BackendExecutionError",
    "BakeRequest",
    "BakeResult",
    "CargoBuild",
    "CompileResult",
    "DebloatConfig",
    "DeploymentError",
    "DotnetBuild",
    "FileChange",
    "GitSource",
    "GoBuild",
    "HttpSource",
    "Image",
    "Kernel",
    "LintError",
    "LockfileError",
    "MeasurementError",
    "MkosiOptions",
    "PolicyError",
    "PlaceholderMeasurementWarning",
    "Policy",
    "Profile",
    "ProfileState",
    "RecipeState",
    "ReproducibilityError",
    "ScriptBuild",
    "SecretSchema",
    "SecretSpec",
    "SecretTarget",
    "SourceBuild",
    "StateError",
    "TdxError",
    "TreeDiff",
    "ValidationError",
    "__version__",
    "load_recipe",
]
