"""Public package entrypoint for the TDX VM SDK.

The declarative API (``Recipe``, ``Fragment``, ``Variant``, the declarations,
``resolve``/``lint``/``lower``/``load``) is the public surface. The fluent
``Image``/``Profile`` names below it remain importable while the compiler is
reached through them; ``Kernel`` is still the fluent kernel spec (the
declarative one is ``tundravm.declarative.Kernel``).
"""

__version__ = "0.1.0"

from .declarative import (
    Build,
    Debloat,
    Declaration,
    Diagnostic,
    Directory,
    Disk,
    File,
    Fragment,
    Git,
    Group,
    Hook,
    Http,
    Init,
    Install,
    Key,
    Mkosi,
    Package,
    Partition,
    Recipe,
    Repository,
    Resolved,
    RuntimeTools,
    Schema,
    Secret,
    SecretEnv,
    SecretFile,
    Secrets,
    Setting,
    Unit,
    User,
    Variant,
    lint,
    load,
    lower,
    resolve,
    resolve_all,
)
from .diff import FileChange, TreeDiff
from .errors import (
    BackendExecutionError,
    DeploymentError,
    LintError,
    LockfileError,
    MeasurementError,
    PolicyError,
    ReproducibilityError,
    StateError,
    TdxError,
    ValidationError,
)
from .image import Image
from .measure import PlaceholderMeasurementWarning
from .measure.model import Measurements
from .models import (
    BakeRequest,
    BakeResult,
    CompileResult,
    DebloatConfig,
    Kernel,
    ProfileState,
    RecipeState,
    SecretSchema,
    SecretSpec,
    SecretTarget,
)
from .options import MkosiOptions
from .policy import Policy
from .profile import Profile
from .recipe import load_recipe
from .source import (
    CargoBuild,
    DotnetBuild,
    GitSource,
    GoBuild,
    HttpSource,
    ScriptBuild,
    SourceBuild,
)

__all__ = [
    # Declarative API
    "Build",
    "Debloat",
    "Declaration",
    "Diagnostic",
    "Directory",
    "Disk",
    "File",
    "Fragment",
    "Git",
    "Group",
    "Hook",
    "Http",
    "Init",
    "Install",
    "Key",
    "Mkosi",
    "Package",
    "Partition",
    "Recipe",
    "Repository",
    "Resolved",
    "RuntimeTools",
    "Schema",
    "Secret",
    "SecretEnv",
    "SecretFile",
    "Secrets",
    "Setting",
    "Unit",
    "User",
    "Variant",
    "lint",
    "load",
    "lower",
    "resolve",
    "resolve_all",
    # Fluent frontend (internal lowering target; removed in a later stage)
    "BackendExecutionError",
    "BakeRequest",
    "BakeResult",
    "CargoBuild",
    "CompileResult",
    "DebloatConfig",
    "DeploymentError",
    "DotnetBuild",
    "FileChange",
    "GitSource",
    "GoBuild",
    "HttpSource",
    "Image",
    "Kernel",
    "LintError",
    "LockfileError",
    "MeasurementError",
    "Measurements",
    "MkosiOptions",
    "PolicyError",
    "PlaceholderMeasurementWarning",
    "Policy",
    "Profile",
    "ProfileState",
    "RecipeState",
    "ReproducibilityError",
    "ScriptBuild",
    "SecretSchema",
    "SecretSpec",
    "SecretTarget",
    "SourceBuild",
    "StateError",
    "TdxError",
    "TreeDiff",
    "ValidationError",
    "__version__",
    "load_recipe",
]
