"""Static shell completion scripts generated from the ``tundravm`` argparse parser.

``render_completion(parser, shell)`` walks the parser's verbs, their flags, flag
choices (``--format``, ``--backend``, ``--scheme``, ``--target``, ...) and
positionals, and returns a bash, zsh or fish script that needs nothing at
completion time: regenerate it with ``tundravm completion SHELL`` after an upgrade.
Path-typed arguments (``RECIPE``, ``MANIFEST``, ``--out``, ``--lockfile``, ...)
complete file names.
"""

from __future__ import annotations

import argparse
import re
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

Shell = Literal["bash", "zsh", "fish"]
SHELLS: tuple[Shell, ...] = ("bash", "zsh", "fish")

INSTALL_HINTS: dict[Shell, str] = {
    "bash": (
        "add `source <(tundravm completion bash)` to ~/.bashrc, or save the output as "
        "~/.local/share/bash-completion/completions/tundravm"
    ),
    "zsh": (
        "add `source <(tundravm completion zsh)` to ~/.zshrc after compinit, or save the "
        "output as _tundravm in a directory on $fpath"
    ),
    "fish": "save the output as ~/.config/fish/completions/tundravm.fish",
}

Value = Literal["none", "word", "file", "dir", "choice"]


@dataclass(frozen=True, slots=True)
class Arg:
    """One flag or positional of a verb, reduced to what a completion script needs."""

    flags: tuple[str, ...]
    """Option strings; empty for a positional."""
    label: str
    help: str
    nargs: int
    """Values the flag takes (0 for a switch)."""
    value: Value
    choices: tuple[str, ...] = ()
    repeat: bool = False
    optional: bool = False


@dataclass(frozen=True, slots=True)
class Verb:
    """One ``tundravm`` subcommand with its arguments."""

    name: str
    help: str
    args: tuple[Arg, ...]

    @property
    def options(self) -> tuple[Arg, ...]:
        return tuple(arg for arg in self.args if arg.flags)

    @property
    def positionals(self) -> tuple[Arg, ...]:
        return tuple(arg for arg in self.args if not arg.flags)


def render_completion(parser: argparse.ArgumentParser, shell: Shell) -> str:
    """The completion script for *shell*, generated from *parser*'s verbs and flags."""
    top = tuple(
        _arg(action) for action in parser._actions if _visible(action) and action.option_strings
    )
    verbs = verbs_of(parser)
    if shell == "bash":
        return _bash(verbs, top)
    if shell == "zsh":
        return _zsh(verbs, top)
    return _fish(verbs, top)


def verbs_of(parser: argparse.ArgumentParser) -> tuple[Verb, ...]:
    """*parser*'s subcommands in declaration order."""
    sub = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    helps = {action.dest: action.help for action in sub._choices_actions}
    return tuple(
        Verb(name, _summary(helps.get(name)), tuple(_arg(a) for a in child._actions if _visible(a)))
        for name, child in sub.choices.items()
    )


def _visible(action: argparse.Action) -> bool:
    return action.help != argparse.SUPPRESS and not isinstance(action, argparse._SubParsersAction)


def _arg(action: argparse.Action) -> Arg:
    choices = tuple(str(choice) for choice in action.choices or ())
    nargs = _count(action.nargs)
    value: Value
    if choices:
        value = "choice"
    elif nargs == 0:
        value = "none"
    elif action.metavar == "DIR" or action.dest == "dir":
        value = "dir"
    elif action.type is Path:
        value = "file"
    else:
        value = "word"
    metavar = action.metavar if isinstance(action.metavar, str) else None
    return Arg(
        flags=tuple(action.option_strings),
        label=(metavar or action.dest).lower().replace("_", "-"),
        help=_summary(action.help),
        nargs=nargs,
        value=value,
        choices=choices,
        repeat=isinstance(action, argparse._AppendAction),
        optional=action.nargs in ("?", "*"),
    )


def _count(nargs: int | str | None) -> int:
    if nargs is None:
        return 1
    if isinstance(nargs, int):
        return nargs
    return 1


def _summary(text: str | None) -> str:
    """The first sentence of a help string, without its ``(default: ...)`` tail."""
    if not text:
        return ""
    first = re.split(r"(?<=\.)\s", text.replace("%(default)s", "-"), maxsplit=1)[0]
    first = re.sub(r";\s*default:[^)]*", "", first)
    first = re.sub(r"\s*\(default:[^)]*\)", "", first)
    return first.rstrip(" .").replace("%%", "%")


def _header(shell: Shell, comment: str = "#") -> list[str]:
    from . import __version__

    return [
        f"{comment} tundravm {__version__} {shell} completion, generated by "
        f"`tundravm completion {shell}`; regenerate it after upgrading tundravm.",
        f"{comment} install: {INSTALL_HINTS[shell]}",
    ]


def _words(items: Iterable[str]) -> str:
    return " ".join(items)


# bash


def _bash(verbs: tuple[Verb, ...], top: tuple[Arg, ...]) -> str:
    first = _words([*(verb.name for verb in verbs), *(f for arg in top for f in arg.flags)])
    lines = [
        *_header("bash"),
        "_tundravm() {",
        "    local cur prev verb i",
        "    COMPREPLY=()",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '    verb=""',
        "    for ((i = 1; i < COMP_CWORD; i++)); do",
        '        if [[ "${COMP_WORDS[i]}" != -* ]]; then',
        '            verb="${COMP_WORDS[i]}"',
        "            break",
        "        fi",
        "    done",
        '    if [[ -z "$verb" ]]; then',
        f'        COMPREPLY=($(compgen -W "{first}" -- "$cur"))',
        "        return 0",
        "    fi",
        '    case "$verb" in',
    ]
    for verb in verbs:
        lines.append(f"        {verb.name})")
        valued = [arg for arg in verb.options if arg.nargs]
        if valued:
            lines.append('            case "$prev" in')
            for arg in valued:
                lines.append(
                    f"                {'|'.join(arg.flags)}) {_bash_values(arg)}; return 0 ;;"
                )
            lines.append("            esac")
        flags = _words(flag for arg in verb.options for flag in arg.flags)
        positional = verb.positionals[0] if verb.positionals else None
        lines += [
            '            if [[ "$cur" == -* ]]; then',
            f'                COMPREPLY=($(compgen -W "{flags}" -- "$cur"))',
            "            else",
            f"                {_bash_values(positional) if positional else ':'}",
            "            fi",
            "            ;;",
        ]
    lines += ["    esac", "}", "complete -o filenames -F _tundravm tundravm", ""]
    return "\n".join(lines)


def _bash_values(arg: Arg) -> str:
    if arg.value == "choice":
        return f'COMPREPLY=($(compgen -W "{_words(arg.choices)}" -- "$cur"))'
    if arg.value == "file":
        return 'COMPREPLY=($(compgen -f -- "$cur"))'
    if arg.value == "dir":
        return 'COMPREPLY=($(compgen -d -- "$cur"))'
    return ":"


# zsh


def _zsh(verbs: tuple[Verb, ...], top: tuple[Arg, ...]) -> str:
    lines = [
        "#compdef tundravm",
        *_header("zsh"),
        "_tundravm() {",
        '    local curcontext="$curcontext" state line',
        "    local -a verbs",
        "    verbs=(",
        *(f"        {_zsh_quote(_zsh_name(verb.name) + ':' + verb.help)}" for verb in verbs),
        "    )",
        "    _arguments -C \\",
        *(f"        {_zsh_option(arg, flag)} \\" for arg in top for flag in arg.flags),
        "        '1:command:->verb' \\",
        "        '*::arg:->args'",
        "    case $state in",
        "        verb)",
        "            _describe -t commands 'tundravm command' verbs",
        "            ;;",
        "        args)",
        "            case $words[1] in",
    ]
    for verb in verbs:
        specs = [_zsh_option(arg, flag) for arg in verb.options for flag in arg.flags]
        specs += [_zsh_positional(index, arg) for index, arg in enumerate(verb.positionals, 1)]
        lines.append(f"                {verb.name})")
        lines.append("                    _arguments \\")
        lines += [f"                        {spec} \\" for spec in specs[:-1]]
        lines.append(f"                        {specs[-1]}")
        lines.append("                    ;;")
    lines += [
        "            esac",
        "            ;;",
        "    esac",
        "}",
        "if [[ $zsh_eval_context[-1] == loadautofunc ]]; then",
        '    _tundravm "$@"',
        "else",
        "    compdef _tundravm tundravm",
        "fi",
        "",
    ]
    return "\n".join(lines)


def _zsh_option(arg: Arg, flag: str) -> str:
    head = ("*" if arg.repeat else "") + flag + f"[{_zsh_text(arg.help)}]"
    values = "".join(f":{_zsh_label(arg, i)}:{_zsh_action(arg)}" for i in range(arg.nargs))
    return _zsh_quote(head + values)


def _zsh_positional(index: int, arg: Arg) -> str:
    colon = "::" if arg.optional else ":"
    return _zsh_quote(f"{index}{colon}{arg.label}:{_zsh_action(arg)}")


def _zsh_label(arg: Arg, index: int) -> str:
    return arg.label if arg.nargs == 1 else f"{arg.label} {index + 1}"


def _zsh_action(arg: Arg) -> str:
    if arg.value == "choice":
        return f"({_words(arg.choices)})"
    if arg.value == "file":
        return "_files"
    if arg.value == "dir":
        return "_files -/"
    return " "


def _zsh_text(text: str) -> str:
    return text.replace("[", "(").replace("]", ")").replace(":", " -")


def _zsh_name(name: str) -> str:
    return name.replace(":", "\\:")


def _zsh_quote(text: str) -> str:
    return "'" + text.replace("'", "'\\''") + "'"


# fish


def _fish(verbs: tuple[Verb, ...], top: tuple[Arg, ...]) -> str:
    lines = [*_header("fish"), "complete -c tundravm -f"]
    root = "__fish_use_subcommand"
    lines += [_fish_option(root, arg) for arg in top]
    lines += [
        f"complete -c tundravm -n {root} -a {verb.name} -d {_fish_quote(verb.help)}"
        for verb in verbs
    ]
    for verb in verbs:
        condition = _fish_quote(f"__fish_seen_subcommand_from {verb.name}")
        lines += [_fish_option(condition, arg) for arg in verb.options]
        if verb.positionals:
            values = _fish_positional(verb.positionals[0])
            if values:
                lines.append(f"complete -c tundravm -n {condition} {values}")
    lines.append("")
    return "\n".join(lines)


def _fish_option(condition: str, arg: Arg) -> str:
    names = [f"-l {flag[2:]}" if flag.startswith("--") else f"-s {flag[1:]}" for flag in arg.flags]
    parts = ["complete -c tundravm -n", condition, *names]
    values = _fish_values(arg) if arg.nargs else ""
    if values:
        parts.append(values)
    elif arg.nargs:
        parts.append("-x")
    if arg.help:
        parts += ["-d", _fish_quote(arg.help)]
    return " ".join(parts)


def _fish_values(arg: Arg) -> str:
    if arg.value == "choice":
        return f"-x -a {_fish_quote(_words(arg.choices))}"
    if arg.value == "file":
        return "-r -F"
    if arg.value == "dir":
        return "-x -a '(__fish_complete_directories)'"
    return ""


def _fish_positional(arg: Arg) -> str:
    if arg.value == "choice":
        return f"-a {_fish_quote(_words(arg.choices))}"
    if arg.value == "file":
        return "-F"
    if arg.value == "dir":
        return "-a '(__fish_complete_directories)'"
    return ""


def _fish_quote(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


__all__ = ["INSTALL_HINTS", "SHELLS", "Arg", "Shell", "Verb", "render_completion", "verbs_of"]
