"""File templates for ``tundravm new`` and ``tundravm init``."""

from __future__ import annotations

BACKEND_SNIPPETS: dict[str, tuple[str, str]] = {
    "lima": (
        "from tundravm.backends import LimaMkosiBackend",
        'LimaMkosiBackend(cpus=6, memory="12GiB", disk="100GiB")',
    ),
    "nix": ("from tundravm.backends import NixMkosiBackend", "NixMkosiBackend()"),
    "local": ("from tundravm.backends import LocalLinuxBackend", "LocalLinuxBackend()"),
    "inprocess": (
        "from tundravm.backends.inprocess import InProcessBackend",
        "InProcessBackend()",
    ),
}

RECIPE_TEMPLATE = """\"\"\"{title} image recipe.

Inspect:  tundravm explain {filename}
Compile:  tundravm compile {filename}
Build:    tundravm bake {filename} --lock
\"\"\"

from tundravm import Debloat, File, Fragment, Package, Recipe, Unit, User, Variant
{backend_import}

APP_UNIT = \"\"\"\\
[Unit]
Description=app

[Service]
User=app
ExecStart=/usr/bin/true

[Install]
WantedBy=minimal.target
\"\"\"

backend = {backend_expr}

recipe = Recipe(
    name="{title}",
    base="{base}",
    common=Fragment(
        "{title}",
        items=(
            Package("systemd"),
            Package("curl"),
            Package("jq"),
            File("/etc/motd", "{title}\\n"),
            User("app", shell="/bin/false"),
            Unit("app.service", APP_UNIT, enabled=True),
            Debloat(),
        ),
    ),
    variants=(
        Variant("default", target="qemu"),
        Variant("dev", parent="default", add=Fragment("dev", items=(Package("strace"),))),
    ),
)
"""

GITIGNORE_MARKER = "/build/*"

GITIGNORE_BLOCK = f"""\
# tundravm build output; the lockfile stays committed for `tundravm lock --check`
{GITIGNORE_MARKER}
!/build/tundravm.lock
"""

WORKFLOW_PATH = ".github/workflows/tundravm.yml"

WORKFLOW_TEMPLATE = """\
# Generated by `tundravm init`. Posts a dry-run summary of the image to the job
# page, then fails when the recipe has findings or the committed mkosi tree or
# lockfile is stale. Findings show inline on the pull request.
name: tundravm

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  recipe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies
        run: uv sync

      - name: Summarize the image
        run: |
          uv run tundravm explain {recipe} --all-profiles --format markdown \\
            >> "$GITHUB_STEP_SUMMARY"

      - name: Check recipe, compiled tree and lockfile
        run: uv run tundravm ci {recipe} --out {out}
"""


def render_recipe_template(*, title: str, filename: str, base: str, backend: str) -> str:
    """Return the starter recipe source for ``tundravm new`` and ``tundravm init``."""
    backend_import, backend_expr = BACKEND_SNIPPETS[backend]
    return RECIPE_TEMPLATE.format(
        title=title,
        filename=filename,
        base=base,
        backend_import=backend_import,
        backend_expr=backend_expr,
    )


def render_workflow(*, recipe: str, out: str = "mkosi") -> str:
    """Return the GitHub Actions workflow ``tundravm init --ci github`` writes."""
    return WORKFLOW_TEMPLATE.format(recipe=recipe, out=out)


__all__ = [
    "BACKEND_SNIPPETS",
    "GITIGNORE_BLOCK",
    "GITIGNORE_MARKER",
    "RECIPE_TEMPLATE",
    "WORKFLOW_PATH",
    "WORKFLOW_TEMPLATE",
    "render_recipe_template",
    "render_workflow",
]
