"""Integration test: SDK emission vs real NethermindEth/nethermind-tdx repo.

Compiles the nethermind_tdx example, clones the upstream repo, and uses
codex exec to compare the two project trees and report differences.
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import subprocess
from pathlib import Path

import pytest

# Import the example without mutating sys.path
_spec = importlib.util.spec_from_file_location(
    "nethermind_tdx",
    Path(__file__).resolve().parent.parent / "examples" / "nethermind_tdx.py",
)
assert _spec and _spec.loader
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
build_nethermind_base = _mod.build_nethermind_base  # type: ignore[attr-defined]

pytestmark = pytest.mark.integration

# Pin upstream to a known commit; override via UPSTREAM_COMMIT env var.
UPSTREAM_COMMIT = os.environ.get(
    "NETHERMIND_TDX_COMMIT", "7ac44e7d9baecf8743a20e75b30fd4ddfce3e85f"
)

# Required section headers that codex must produce in the report.
REQUIRED_SECTIONS = [
    "## Files only in upstream",
    "## Files only in SDK",
    "## Files in both with differences",
    "## Files that match exactly",
    "## Summary",
]


@pytest.fixture(scope="module")
def sdk_output(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Compile the nethermind-tdx example once."""
    img = build_nethermind_base()
    out = tmp_path_factory.mktemp("sdk_emission")
    img.compile(out / "mkosi")
    return out / "mkosi"


@pytest.fixture(scope="module")
def upstream_repo(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Clone NethermindEth/nethermind-tdx at a pinned commit."""
    if not shutil.which("git"):
        pytest.skip("git not available")
    repo_dir = tmp_path_factory.mktemp("upstream") / "nethermind-tdx"
    subprocess.run(
        [
            "git",
            "clone",
            "https://github.com/NethermindEth/nethermind-tdx.git",
            str(repo_dir),
        ],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "-C", str(repo_dir), "checkout", UPSTREAM_COMMIT],
        check=True,
        capture_output=True,
    )
    return repo_dir


def test_compare_with_upstream(
    sdk_output: Path,
    upstream_repo: Path,
    tmp_path: Path,
) -> None:
    """Use codex to compare SDK output against upstream and report differences."""
    if not shutil.which("codex"):
        pytest.skip("codex CLI not available")

    report_file = tmp_path / "comparison_report.md"

    prompt = f"""\
Compare these two mkosi project trees and produce a structured markdown report
of ALL differences.

SDK output (generated by tdxvm SDK):
  {sdk_output}/default/

Upstream repo (NethermindEth/nethermind-tdx base layer, commit {UPSTREAM_COMMIT}):
  {upstream_repo}/base/

The SDK output is a compiled mkosi project tree. The upstream repo is the
source of truth.

IMPORTANT semantic mappings — the SDK synthesises scripts from upstream concepts:
- upstream `debloat-systemd.sh` (PostInstallationScript) → SDK `scripts/*-postinst.sh`
- upstream `debloat.sh` (FinalizeScript) → SDK `scripts/*-finalize.sh`
- upstream `add-backports.sh` (SyncScript) → SDK uses SandboxTrees mount (no script)
- upstream `efi-stub.sh` → not modelled (deployment-specific)
- upstream `remove-image-version.sh` → not modelled (deployment-specific)
- SDK `scripts/*-build.sh` → corresponds to upstream overlay build scripts (tdxs)
- SDK `mkosi.extra/` → corresponds to upstream overlay extra trees (tdxs config/units)

Instructions:
1. Read every file in both directories recursively
2. For each file in upstream base/, find the corresponding SDK output file
   using the semantic mappings above
3. Compare them line by line where correspondence exists
4. List files that exist in upstream but not in SDK output (note if intentional)
5. List files that exist in SDK output but not in upstream (note if from tdxs module)
6. For files that exist in both, show exact diffs

Output format — write a markdown report to {report_file} with these sections:
- ## Files only in upstream
- ## Files only in SDK
- ## Files in both with differences (show inline diffs)
- ## Files that match exactly
- ## Summary: total files compared, matches, differences, intentional gaps

Be thorough and precise. Read every file completely.
Write the report to {report_file}."""

    result = subprocess.run(
        [
            "codex",
            "exec",
            "--dangerously-bypass-approvals-and-sandbox",
            prompt,
        ],
        capture_output=True,
        text=True,
        timeout=300,
    )

    # codex must exit cleanly
    assert result.returncode == 0, (
        f"codex exited with {result.returncode}.\n"
        f"stdout: {result.stdout[-2000:]}\n"
        f"stderr: {result.stderr[-2000:]}"
    )

    assert report_file.exists(), (
        f"codex did not produce report.\n"
        f"stdout: {result.stdout[-2000:]}\n"
        f"stderr: {result.stderr[-2000:]}"
    )

    report = report_file.read_text(encoding="utf-8")
    print(report)  # Always print for visibility in pytest -s

    # Verify the report has the required structure
    for section in REQUIRED_SECTIONS:
        assert section in report, f"Report missing required section: {section}"
