"""Nethermind TDX base layer — reproduces the NethermindEth/nethermind-tdx base image.

This example shows how to declare an image matching the real nethermind-tdx
base layer (https://github.com/NethermindEth/nethermind-tdx), including:

- Debian Trixie with UKI output and reproducible builds
- Real kernel build from source with config file
- EFI stub pinning from Debian snapshot for reproducible boot
- Dynamic backports source generation
- Skeleton files: custom init, static DNS, minimal.target, network DHCP
- Full systemd debloat (binary stripping, unit masking, path removal)
- Tdxs quote service module (build from source, config, systemd units)

The SDK's integration tests verify this configuration produces output that
matches the upstream repo file-for-file (see integration_tests/).
"""

from tdx import Image, Kernel
from tdx.modules.tdxs import Tdxs

# ── Upstream constants ────────────────────────────────────────────────

PINNED_MIRROR = "https://snapshot.debian.org/archive/debian/20251113T083151Z/"

KERNEL_CMDLINE = (
    "console=tty0 console=ttyS0,115200n8 "
    "mitigations=auto,nosmt "
    "spec_store_bypass_disable=on "
    "nospectre_v2"
)

NETWORK_SETUP_SERVICE = """\
[Unit]
Description=Basic Network Setup
DefaultDependencies=no
Before=network.target
Wants=network.target

[Service]
Type=oneshot
ExecStart=ip link set lo up
ExecStart=ip link set eth0 up
ExecStart=chattr +i /etc/resolv.conf
ExecStart=/usr/sbin/udhcpc -i eth0 -n
RemainAfterExit=yes

[Install]
WantedBy=sysinit.target"""


# ── Image definition ──────────────────────────────────────────────────


def build_nethermind_base() -> Image:
    img = Image(
        base="debian/trixie",
        reproducible=True,
        with_network=True,
        clean_package_metadata=True,
        manifest_format="json",
        init_script=Image.DEFAULT_TDX_INIT,
        seed="630b5f72-a36a-4e83-b23d-6ef47c82fd9c",
        output_directory="build",
        package_cache_directory="mkosi.cache",
        environment_passthrough=("KERNEL_IMAGE", "KERNEL_VERSION"),
    )

    # Real kernel build from source with hardened command line
    img.kernel = Kernel.tdx_kernel(
        "6.13.12",
        cmdline=KERNEL_CMDLINE,
        config_file="kernel/kernel-yocto.config",
        source_repo="https://github.com/gregkh/linux",
    )

    # Reproducibility hooks
    # strip_image_version() is auto-called by reproducible=True
    img.efi_stub(
        snapshot_url=PINNED_MIRROR,
        package_version="255.4-1",
    )
    img.backports()

    # Runtime packages
    img.install(
        "kmod",
        "systemd",
        "systemd-boot-efi",
        "busybox",
        "util-linux",
        "procps",
        "ca-certificates",
        "openssl",
        "iproute2",
        "udhcpc",
        "e2fsprogs",
    )

    # Build-time packages (stripped from final image)
    img.build_install(
        "build-essential",
        "git",
        "curl",
        "cmake",
        "pkg-config",
        "clang",
        "cargo/sid",
        "flex",
        "bison",
        "elfutils",
        "bc",
        "perl",
        "gawk",
        "zstd",
        "libssl-dev",
        "libelf-dev",
    )

    # Skeleton: files placed before package manager runs (no trailing newline)
    img.skeleton("/etc/resolv.conf", content="nameserver 8.8.8.8\nnameserver 8.8.4.4")
    img.skeleton("/etc/systemd/system/network-setup.service", content=NETWORK_SETUP_SERVICE)
    # minimal.target is auto-generated by debloat

    # Aggressive debloat: strip systemd binaries/units, remove docs/caches
    img.debloat(enabled=True)

    # TDX quote service: builds from source, adds config + systemd units
    Tdxs(issuer_type="dcap").apply(img)

    return img


if __name__ == "__main__":
    img = build_nethermind_base()
    img.compile("build/mkosi")
    img.lock()
    img.bake(frozen=True)
