"""The declarative frontend: immutable recipes, resolved and lowered onto the compiler.

A :class:`Recipe` is an immutable value: recipe-wide settings, a ``common``
:class:`Fragment` of declarations and the :class:`Variant` overlays.
:func:`resolve` expands one variant, :func:`lint` reports every problem as a
:class:`Diagnostic`, and :func:`lower` builds the compiler's ``Image`` from it,
which every CLI command consumes.
"""

from .load import load
from .lower import lower
from .model import (
    Build,
    Check,
    Debloat,
    Declaration,
    Diagnostic,
    Directory,
    Disk,
    File,
    Fragment,
    Git,
    Group,
    Hook,
    Http,
    Init,
    Install,
    Kernel,
    Key,
    Mkosi,
    Package,
    Pairs,
    Partition,
    Phase,
    Recipe,
    Repository,
    Resolved,
    RuntimeTools,
    Schema,
    Secret,
    SecretEnv,
    SecretFile,
    Secrets,
    Setting,
    Target,
    Unit,
    User,
    Variant,
)
from .resolve import identity, lint, resolve, resolve_all

__all__ = [
    "Build",
    "Check",
    "Debloat",
    "Declaration",
    "Diagnostic",
    "Directory",
    "Disk",
    "File",
    "Fragment",
    "Git",
    "Group",
    "Hook",
    "Http",
    "Init",
    "Install",
    "Kernel",
    "Key",
    "Mkosi",
    "Package",
    "Pairs",
    "Partition",
    "Phase",
    "Recipe",
    "Repository",
    "Resolved",
    "RuntimeTools",
    "Schema",
    "Secret",
    "SecretEnv",
    "SecretFile",
    "Secrets",
    "Setting",
    "Target",
    "Unit",
    "User",
    "Variant",
    "identity",
    "lint",
    "load",
    "lower",
    "resolve",
    "resolve_all",
]
