"""The declarative frontend: immutable recipes, resolved and lowered onto the compiler.

A :class:`Recipe` is an immutable value: recipe-wide settings, a ``common``
:class:`Fragment` of declarations and the :class:`Variant` overlays.
:func:`resolve` expands one variant, :func:`lint` reports every problem as a
:class:`Diagnostic`, and :func:`lower` builds the compiler's ``Image`` from it,
which every CLI command consumes. The lifecycle (:func:`compile`, :func:`lint`,
:func:`lock`, :func:`bake`, :func:`measure`, :func:`deploy`, :func:`doctor`)
takes a recipe and explicit inputs and returns explicit results.
"""

from .lifecycle import (
    Artifact,
    Azure,
    Backend,
    Deployment,
    Entry,
    Gcp,
    Lock,
    Measurements,
    Pin,
    Qemu,
    Tree,
    bake,
    compile,
    deploy,
    diff,
    doctor,
    lint,
    lock,
    lock_status,
    measure,
    read_artifacts,
    read_lock,
    write_lock,
)
from .load import load
from .lower import lower
from .model import (
    Build,
    Check,
    Debloat,
    Declaration,
    Diagnostic,
    Directory,
    Disk,
    File,
    Fragment,
    Git,
    Group,
    Hook,
    Http,
    Init,
    Install,
    Kernel,
    Key,
    Mkosi,
    Package,
    Pairs,
    Partition,
    Phase,
    Recipe,
    Repository,
    Resolved,
    RuntimeTools,
    Schema,
    Secret,
    SecretEnv,
    SecretFile,
    Secrets,
    Setting,
    Target,
    Unit,
    User,
    Variant,
)
from .modules import backports, devtools, efi_stub, tdxs
from .resolve import identity, resolve, resolve_all

__all__ = [
    "Artifact",
    "Azure",
    "Backend",
    "Build",
    "Check",
    "Debloat",
    "Declaration",
    "Deployment",
    "Diagnostic",
    "Directory",
    "Disk",
    "Entry",
    "File",
    "Fragment",
    "Gcp",
    "Git",
    "Group",
    "Hook",
    "Http",
    "Init",
    "Install",
    "Kernel",
    "Key",
    "Lock",
    "Measurements",
    "Mkosi",
    "Package",
    "Pairs",
    "Partition",
    "Phase",
    "Pin",
    "Qemu",
    "Recipe",
    "Repository",
    "Resolved",
    "RuntimeTools",
    "Schema",
    "Secret",
    "SecretEnv",
    "SecretFile",
    "Secrets",
    "Setting",
    "Target",
    "Tree",
    "Unit",
    "User",
    "Variant",
    "backports",
    "bake",
    "compile",
    "deploy",
    "devtools",
    "diff",
    "doctor",
    "efi_stub",
    "identity",
    "lint",
    "load",
    "lock",
    "lock_status",
    "lower",
    "measure",
    "read_artifacts",
    "read_lock",
    "resolve",
    "resolve_all",
    "tdxs",
    "write_lock",
]
