"""Azure platform profile.

Adds Azure-specific provisioning, dmidecode, and VHD postoutput to an Image
within an ``img.profile("azure")`` context.  The VHD postoutput script is
auto-generated by the SDK when ``generate_cloud_postoutput=True`` (default)
and the profile's output_targets include ``"azure"``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tdx.image import Image

# ---------------------------------------------------------------------------
# Azure provisioning completion script
# ---------------------------------------------------------------------------

AZURE_PROVISIONING_SCRIPT = """\
#!/bin/bash
set -euo pipefail

# Azure provisioning completion script
# Reports VM health to the Azure fabric controller (wireserver)

WIRESERVER="168.63.129.16"
MAX_RETRIES=5

# Only run on Azure (check DMI for Microsoft Corporation)
MANUFACTURER=$(dmidecode -s system-manufacturer 2>/dev/null || true)
if [[ "$MANUFACTURER" != *"Microsoft Corporation"* ]]; then
    echo "Not running on Azure, skipping provisioning completion"
    exit 0
fi

get_goal_state() {
    curl -s -H "x-ms-version: 2012-11-30" \
        "http://${WIRESERVER}/machine/?comp=goalstate" 2>/dev/null
}

send_health() {
    local container_id="$1"
    local instance_id="$2"

    local health_xml="<?xml version=\\"1.0\\" encoding=\\"utf-8\\"?>
<Health>
  <GoalStateIncarnation>1</GoalStateIncarnation>
  <Container>
    <ContainerId>${container_id}</ContainerId>
    <RoleInstanceList>
      <Role>
        <InstanceId>${instance_id}</InstanceId>
        <Health>
          <State>Ready</State>
        </Health>
      </Role>
    </RoleInstanceList>
  </Container>
</Health>"

    curl -s -X POST \
        -H "x-ms-version: 2012-11-30" \
        -H "Content-Type: text/xml; charset=utf-8" \
        -d "$health_xml" \
        "http://${WIRESERVER}/machine/?comp=health" 2>/dev/null
}

for i in $(seq 1 "$MAX_RETRIES"); do
    echo "Attempt $i/$MAX_RETRIES: Retrieving goal state..."

    GOAL_STATE=$(get_goal_state) || true

    if [ -z "$GOAL_STATE" ]; then
        echo "Failed to retrieve goal state"
        if [ "$i" -lt "$MAX_RETRIES" ]; then
            sleep 5
            continue
        fi
        echo "Exhausted retries, exiting"
        exit 1
    fi

    CONTAINER_ID=$(echo "$GOAL_STATE" | \\
        sed -n 's/.*<ContainerId>\\(.*\\)<\\/ContainerId>.*/\\1/p' | head -1)
    INSTANCE_ID=$(echo "$GOAL_STATE" | \\
        sed -n 's/.*<InstanceId>\\(.*\\)<\\/InstanceId>.*/\\1/p' | head -1)

    if [ -z "$CONTAINER_ID" ] || [ -z "$INSTANCE_ID" ]; then
        echo "Failed to parse goal state"
        if [ "$i" -lt "$MAX_RETRIES" ]; then
            sleep 5
            continue
        fi
        echo "Exhausted retries, exiting"
        exit 1
    fi

    echo "Sending health report (container=$CONTAINER_ID, instance=$INSTANCE_ID)..."
    if send_health "$CONTAINER_ID" "$INSTANCE_ID"; then
        echo "Successfully reported Health/Ready to Azure fabric controller"
        exit 0
    fi

    echo "Failed to send health report"
    if [ "$i" -lt "$MAX_RETRIES" ]; then
        sleep 5
    fi
done

echo "Exhausted retries, exiting"
exit 1
"""

# ---------------------------------------------------------------------------
# Systemd service unit for azure-complete-provisioning
# ---------------------------------------------------------------------------

AZURE_PROVISIONING_SERVICE = """\
[Unit]
Description=Azure Provisioning Completion
After=network.target network-setup.service
Requires=network-setup.service

[Service]
Type=oneshot
ExecStart=/usr/bin/azure-complete-provisioning
RemainAfterExit=yes

[Install]
WantedBy=minimal.target
"""


@dataclass(slots=True)
class AzurePlatform:
    """Azure platform profile.

    Adds:
    * ``dmidecode`` runtime package
    * ``/usr/bin/azure-complete-provisioning`` executable script
    * ``azure-complete-provisioning.service`` systemd unit
    * Service enablement + symlink into ``minimal.target.wants/``
    * ``"azure"`` output target (triggers VHD postoutput auto-generation)
    """

    def apply(self, image: Image) -> None:
        """Populate the active Azure profile on *image*.

        Must be called inside an ``img.profile("azure")`` context::

            with img.profile("azure"):
                AzurePlatform().apply(img)
        """
        # Runtime package
        image.install("dmidecode")

        # Provisioning completion script
        image.file(
            "/usr/bin/azure-complete-provisioning",
            content=AZURE_PROVISIONING_SCRIPT,
            mode="0755",
        )

        # Systemd service unit
        image.file(
            "/usr/lib/systemd/system/azure-complete-provisioning.service",
            content=AZURE_PROVISIONING_SERVICE,
        )

        # Enable the service and symlink into minimal.target.wants
        image.run(
            "mkosi-chroot",
            "systemctl",
            "enable",
            "azure-complete-provisioning.service",
            phase="postinst",
        )
        image.run(
            "mkosi-chroot",
            "mkdir",
            "-p",
            "/etc/systemd/system/minimal.target.wants",
            phase="postinst",
        )
        image.run(
            "mkosi-chroot",
            "ln",
            "-sf",
            "/usr/lib/systemd/system/azure-complete-provisioning.service",
            "/etc/systemd/system/minimal.target.wants/azure-complete-provisioning.service",
            phase="postinst",
        )

        # Output target — triggers VHD postoutput script auto-generation
        image.output_targets("azure")
