"""GCP platform profile.

Adds GCP-specific DNS configuration, udev rules, and tar.gz postoutput to an
Image within an ``img.profile("gcp")`` context.  The tar.gz postoutput script
is auto-generated by the SDK when ``generate_cloud_postoutput=True`` (default)
and the profile's output_targets include ``"gcp"``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tundravm.image import Image

# ---------------------------------------------------------------------------
# /etc/hosts — GCP metadata server DNS entries
# ---------------------------------------------------------------------------

GCP_HOSTS = """\
127.0.0.1 localhost
169.254.169.254 metadata.google.internal metadata"""

# ---------------------------------------------------------------------------
# /etc/resolv.conf — GCP DNS resolver
# ---------------------------------------------------------------------------

GCP_RESOLV_CONF = """\
nameserver 169.254.169.254
options edns0 trust-ad"""

# ---------------------------------------------------------------------------
# 65-gce-disk-naming.rules — udev rules for GCE persistent disk naming
# ---------------------------------------------------------------------------

GCE_DISK_NAMING_RULES = """\
# Google Compute Engine persistent disk naming rules

# SCSI persistent disks
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="sd*[!0-9]", IMPORT{program}="scsi_id --export --whitelisted -d /dev/%k", ENV{ID_SERIAL_SHORT}=="?*", SYMLINK+="disk/by-id/google-$env{ID_SERIAL_SHORT}"
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="sd*", ATTR{partition}=="?*", IMPORT{parent}=="ID_SERIAL_SHORT", ENV{ID_SERIAL_SHORT}=="?*", SYMLINK+="disk/by-id/google-$env{ID_SERIAL_SHORT}-part%n"

# SCSI local SSDs
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="sd*[!0-9]", ATTRS{model}=="EphemeralDisk   ", PROGRAM="scsi_id --whitelisted --export -d /dev/%k", SYMLINK+="disk/by-id/google-local-ssd-$env{ID_SERIAL_SHORT}"
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="sd*", ATTRS{model}=="EphemeralDisk   ", ATTR{partition}=="?*", PROGRAM="scsi_id --whitelisted --export -d /dev/%k", SYMLINK+="disk/by-id/google-local-ssd-$env{ID_SERIAL_SHORT}-part%n"

# NVMe persistent disks
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="nvme*n*", ATTRS{model}=="nvme_card-pd", PROGRAM="/usr/lib/udev/google_nvme_id %k", SYMLINK+="disk/by-id/google-%c"
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="nvme*n*p*", ATTRS{model}=="nvme_card-pd", PROGRAM="/usr/lib/udev/google_nvme_id %k", SYMLINK+="disk/by-id/google-%c-part%n"

# NVMe local SSDs
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="nvme*n*", ATTRS{model}=="nvme_card        ", PROGRAM="/usr/lib/udev/google_nvme_id %k", SYMLINK+="disk/by-id/google-local-nvme-ssd-%c"
ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="nvme*n*p*", ATTRS{model}=="nvme_card        ", PROGRAM="/usr/lib/udev/google_nvme_id %k", SYMLINK+="disk/by-id/google-local-nvme-ssd-%c-part%n"
"""

# ---------------------------------------------------------------------------
# google_nvme_id — helper script for NVMe disk identification
# ---------------------------------------------------------------------------

GOOGLE_NVME_ID = """\
#!/bin/bash
# Google NVMe ID helper for udev
# Extracts disk serial from NVMe namespace for /dev/disk/by-id symlinks

set -euo pipefail

DISK="$1"

# Strip partition suffix to get the namespace device
NAMESPACE="${DISK%%p*}"

# Read the serial from sysfs
SERIAL=$(cat "/sys/class/block/${NAMESPACE}/device/serial" 2>/dev/null) || exit 1

if [[ -z "$SERIAL" ]]; then
    exit 1
fi

# Trim trailing whitespace
echo "${SERIAL}" | sed 's/[[:space:]]*$//'
"""


@dataclass(slots=True)
class GcpPlatform:
    """GCP platform profile.

    Adds:
    * ``udev`` runtime package
    * ``/etc/hosts`` with GCP metadata server entries
    * ``/etc/resolv.conf`` with GCP DNS resolver
    * ``/usr/lib/udev/rules.d/65-gce-disk-naming.rules`` udev rules
    * ``/usr/lib/udev/google_nvme_id`` NVMe disk ID helper script
    * ``"gcp"`` output target (triggers tar.gz postoutput auto-generation)
    """

    def apply(self, image: Image) -> None:
        """Populate the active GCP profile on *image*.

        Must be called inside an ``img.profile("gcp")`` context::

            with img.profile("gcp"):
                GcpPlatform().apply(img)
        """
        # Runtime package
        image.install("udev")

        # DNS / metadata configuration files
        image.file("/etc/hosts", content=GCP_HOSTS)
        image.file("/etc/resolv.conf", content=GCP_RESOLV_CONF)

        # Udev rules for GCE disk naming
        image.file(
            "/usr/lib/udev/rules.d/65-gce-disk-naming.rules",
            content=GCE_DISK_NAMING_RULES,
        )

        # NVMe ID helper script
        image.file(
            "/usr/lib/udev/google_nvme_id",
            content=GOOGLE_NVME_ID,
            mode="0755",
        )

        # Output target — triggers tar.gz postoutput script auto-generation
        image.output_targets("gcp")
